### ISSUE TITLE
How to use currentColor?

### ISSUE THREAD

**Issue by dexcell** [aniftyco/tailwindcss-spinner#11]
I want to use this spinner like we use `fill-current` on svg like this:
````
<div class="spinner-current text-indigo-600"></div>
````

However it doesn't work, any helps?

My tailwind config
````
module.exports = {
  theme: {
    spinner: (theme) => ({
      current: {
        color: 'currentColor',
        size: '2em', // size of the spinner (used for both width and height)
        border: '2px', // border-width of the spinner (shouldn't be bigger than half the spinner's size)
        speed: '800ms', // the speed at which the spinner should rotate
      },
    }),
  },
  variants: {
    spinner: ['responsive'],
  },
  plugins: [
    require('tailwindcss-spinner')(),
  ]
}
````

**Comment by kerns** [comment]
I'm similarly interested in adapting the color to different contexts without editing tailwindconfig.js

**Comment by dexcell** [comment]
I'm using `tailwindcss-plugin-delight` now, seems does the job. But i hope this package get updated.

**Comment by joshmanders** [comment]
@dexcell 
> I'm using `tailwindcss-plugin-delight` now, seems does the job. But i hope this package get updated.

I've got plans to give this plugin some love including updates. In the meantime, PR's for functionality, etc are fully welcome.

**Comment by kerns** [comment]
Hope to see this happen.
