### ISSUE TITLE
Should we deprecate this package?

### ISSUE THREAD

**Issue by joshmanders** [aniftyco/tailwindcss-spinner#13]
Tailwind now has spinning functionality with the new animations additions, should we deprecate this package?

https://github.com/aniftyco/awesome-tailwindcss/pull/274

Thoughts @hacknug @innocenzi

**Comment by innocenzi** [comment]
I think so—given the fact that Tailwind has this functionality, would you use this package? I don't think I would, but if you do, maybe you shouldn't deprecate it

**Comment by joshmanders** [comment]
I don't think I will now that it's part of core. I won't delete the repo or anything, just deprecate the package and then archive the repo.

**Comment by joshmanders** [comment]
Yeah I'm gonna deprecate this today.
