### ISSUE TITLE
Adding another !important

### ISSUE THREAD

**Issue by pwnz22** [aniftyco/tailwindcss-spinner#7]
Adding another `!important` if i have tailwind `important: true` option.
![erorr image](https://i.imgur.com/u31e974.png)

**Comment by hacknug** [comment]
Hey @pwnz22! 👋 

Thanks for reporting this. It was actually a bug in `postcss-js` parser that has now been fixed. Running `npm i` on your project (or the equivalent if you use yarn, pnpm or something else) should solve your issue. I've also added tests to the plugin to catch this in case we have a regression at some point.

Please, confirm it now works correctly and thank you again for pointing this out!

**Comment by pwnz22** [comment]
Hi hacknug!

Thank you!
