### ISSUE TITLE
Just blank when i call class="spinner"? how to use that

### ISSUE THREAD

**Issue by ghost** [aniftyco/tailwindcss-spinner#9]

**Comment by HugoDF** [comment]
@kevinaltaf have you tried adding the `theme.spinner` to your tailwind config?

**Comment by hroland** [comment]
@kevariable if you apply `theme.spinner.default.color` (like in the readme) it works.
They way its set up is weird thought.. `.spinner` has `color: transparent !important` set, and .spinner:after has its color come from `currentColor`. So it always pulls transparent and never the actual text color.. 🤷‍♂️
